adminPrivateWarps: true
loadChunks: false
warpSafety:
  enabled: true
  searchRadius: 5
  verticalTolerance: 5
limits:
  default:
    maxTotal: 15
    maxPublic: 5
    maxPrivate: 10
  user:
    maxTotal: 8
    maxPublic: 4
    maxPrivate: 4
mysql:
  enabled: false
  host: 'localhost'
  port: 3306
  database: 'minecraft'
  table: 'warpTable'
  username: 'root'
  password: 'password'